'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type SupportedLanguage = 'en' | 'ta' | 'hi' | 'es' | 'fr' | 'ar' | 'ja';

export const DICTIONARY: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    exploreSpots: 'EXPLORE SPOTS',
    inAppMap: 'MAP',
    liveRadar: 'LIVE RADAR',
    foodieReels: 'FOODIE REELS',
    collections: 'COLLECTIONS',
    cravings: 'CRAVINGS?',
    defaultLocation: 'DEFAULT LOCATION',
    subCravings: 'What are you craving today?',
    searchPlaceholder: 'Search for restaurants, cuisines, or dishes...',
    whatsOnMind: "WHAT'S ON YOUR MIND?",
    topRestaurants: 'TOP RESTAURANT CHAINS NEAR YOU',
    restaurantsExplore: 'RESTAURANTS TO EXPLORE RIGHT NOW',
    filters: 'FILTERS',
    sort: 'SORT',
    kitchenDashboard: 'Kitchen Dashboard',
    driverPortal: 'Driver Portal',
    cat_Idli: 'Idli',
    cat_Dosa: 'Dosa',
    cat_Biryani: 'Biryani',
    cat_Meals: 'Meals',
    cat_Sweets: 'Sweets',
    cat_Snacks: 'Snacks',
    cat_Chaat: 'Chaat',
    cat_Coffee: 'Coffee',

    // Settings Keys
    settingsTitle: 'Settings & Profile Controls',
    settingsSub: 'DINER WORKSPACE CONFIGURATION',
    accountProfile: 'Account & Profile',
    langRegional: 'Language & Regional',
    locRadius: 'Location & Radius',
    pushNotifications: 'Push Notifications',
    appearanceTheme: 'Appearance & Theme',
    mapsNav: 'Maps & Navigation',
    paymentsHist: 'Payments & History',
    rewardsPassport: 'Rewards & Passport',
    socialFriends: 'Friends & Social',
    privacySecurity: 'Privacy & Security',
    supportFeedback: 'Support & Feedback',
    legalNorms: 'Legal (Govt Norms)',
    aboutEats: 'About Hidden Eats',
    saveSettings: 'Save All Settings & Preferences',
    primaryLangLabel: 'Primary Site Language (7 Curated Languages)',
    primaryLangSub: 'Select your preferred language for instant 0ms page translation.',
    autoGoogleLabel: 'Automated Google Machine Translation (100+ Languages)',
    autoGoogleSub: 'Translates user reviews and dish announcements into over 100 global languages.',
    currencyDisplay: 'Preferred Currency Display',
  },
  ta: {
    exploreSpots: 'உணவகங்கள்',
    inAppMap: 'வரைபடம்',
    liveRadar: 'லைவ் ரேடார்',
    foodieReels: 'உணவு ரீல்ஸ்',
    collections: 'சேகரிப்புகள்',
    cravings: 'பசி எடுக்கிறதா?',
    defaultLocation: 'இயல்புநிலை இருப்பிடம்',
    subCravings: 'இன்று என்ன உணவு சாப்பிட விருப்பம்?',
    searchPlaceholder: 'உணவகங்கள், ரகசிய உணவுகளைத் தேடுங்கள்...',
    whatsOnMind: 'உங்களுக்கு என்ன உணவு பிடிக்கும்?',
    topRestaurants: 'உங்கள் அருகிலுள்ள சிறந்த உணவகங்கள்',
    restaurantsExplore: 'தற்போது ஆராய சிறந்த உணவகங்கள்',
    filters: 'வடிகட்டிகள்',
    sort: 'வரிசைப்படுத்து',
    kitchenDashboard: 'சமையலறை பலகை',
    driverPortal: 'டெலிவரி போர்ட்டல்',
    cat_Idli: 'இட்லி',
    cat_Dosa: 'தோசை',
    cat_Biryani: 'பிரியாணி',
    cat_Meals: 'சாப்பாடு',
    cat_Sweets: 'இனிப்புகள்',
    cat_Snacks: 'சிற்றுண்டி',
    cat_Chaat: 'சாட்',
    cat_Coffee: 'காபி',

    // Settings Keys
    settingsTitle: 'அமைப்புகள் & சுயவிவரக் கட்டுப்பாடு',
    settingsSub: 'உணவுப்பிரியர் பணியிட அமைப்பு',
    accountProfile: 'கணக்கு & சுயவிவரம்',
    langRegional: 'மொழி & பிராந்தியம்',
    locRadius: 'இருப்பிடம் & ஆரம்',
    pushNotifications: 'அறிவிப்புகள்',
    appearanceTheme: 'தோற்றம் & தீம்',
    mapsNav: 'வரைபடம் & வழிசெலுத்தல்',
    paymentsHist: 'பணம் செலுத்துதல் & வரலாறு',
    rewardsPassport: 'வெகுமதிகள் & பாஸ்போர்ட்',
    socialFriends: 'நண்பர்கள் & சமூகம்',
    privacySecurity: 'தனியுரிமை & பாதுகாப்பு',
    supportFeedback: 'ஆதரவு & கருத்து',
    legalNorms: 'சட்டம் (அரசு விதிகள்)',
    aboutEats: 'Hidden Eats பற்றி',
    saveSettings: 'அனைத்து அமைப்புகளையும் சேமிக்கவும்',
    primaryLangLabel: 'முதன்மை தள மொழி (7 தேர்ந்தெடுக்கப்பட்ட மொழிகள்)',
    primaryLangSub: 'உடனடி மொழிபெயர்ப்பிற்கு உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.',
    autoGoogleLabel: 'தானியங்கி கூகிள் இயந்திர மொழிபெயர்ப்பு (100+ மொழிகள்)',
    autoGoogleSub: '100 க்கும் மேற்பட்ட மொழிகளில் கருத்துக்களை தானாக மொழிபெயர்க்கிறது.',
    currencyDisplay: 'விருப்பமான நாணயக் காட்சி',
  },
  hi: {
    exploreSpots: 'रेस्टोरेंट खोजें',
    inAppMap: 'नक्शा',
    liveRadar: 'लाइव राडार',
    foodieReels: 'फुडी रील्स',
    collections: 'संग्रह',
    cravings: 'भूख लगी है?',
    defaultLocation: 'डीफ़ॉल्ट स्थान',
    subCravings: 'आज आपका क्या खाने का मन है?',
    searchPlaceholder: 'रेस्तरां, व्यंजन या गुप्त व्यंजन खोजें...',
    whatsOnMind: 'आज आपका क्या खाने का मन है?',
    topRestaurants: 'आपके पास के शीर्ष रेस्टोरेंट',
    restaurantsExplore: 'अभी खोजे जाने वाले शीर्ष रेस्टोरेंट',
    filters: 'फिल्टर',
    sort: 'क्रमबद्ध करें',
    kitchenDashboard: 'रसोई डैशबोर्ड',
    driverPortal: 'डिलिवरी पोर्टल',
    cat_Idli: 'इडली',
    cat_Dosa: 'डोसा',
    cat_Biryani: 'बिरयानी',
    cat_Meals: 'थाली / भोजन',
    cat_Sweets: 'मिठाई',
    cat_Snacks: 'स्नैक्स',
    cat_Chaat: 'चाट',
    cat_Coffee: 'कॉफ़ी',

    // Settings Keys
    settingsTitle: 'सेटिंग्स और प्रोफ़ाइल नियंत्रण',
    settingsSub: 'डाइनर कार्यस्थान कॉन्फ़िगरेशन',
    accountProfile: 'खाता और प्रोफ़ाइल',
    langRegional: 'भाषा और क्षेत्रीय',
    locRadius: 'स्थान और त्रिज्या',
    pushNotifications: 'पुश सूचनाएं',
    appearanceTheme: 'प्रकटन और थीम',
    mapsNav: 'मानचित्र और नेविगेशन',
    paymentsHist: 'भुगतान और इतिहास',
    rewardsPassport: 'पुरस्कार और पासपोर्ट',
    socialFriends: 'मित्र और सामाजिक',
    privacySecurity: 'गोपनीयता और सुरक्षा',
    supportFeedback: 'सहायता और प्रतिक्रिया',
    legalNorms: 'कानूनी (सरकारी नियम)',
    aboutEats: 'Hidden Eats के बारे में',
    saveSettings: 'सभी सेटिंग्स और प्राथमिकताएं सहेजें',
    primaryLangLabel: 'प्राथमिक साइट भाषा (7 चुनिंदा भाषाएं)',
    primaryLangSub: 'त्वरित अनुवाद के लिए अपनी पसंदीदा भाषा चुनें।',
    autoGoogleLabel: 'स्वचालित Google मशीन अनुवाद (100+ भाषाएं)',
    autoGoogleSub: 'उपयोगकर्ता समीक्षाओं का 100 से अधिक भाषाओं में अनुवाद करता है।',
    currencyDisplay: 'पसंदीदा मुद्रा प्रदर्शन',
  },
  es: {
    exploreSpots: 'EXPLORAR LUGARES',
    inAppMap: 'MAPA',
    liveRadar: 'RADAR EN VIVO',
    foodieReels: 'REELS DE COMIDA',
    collections: 'COLECCIONES',
    cravings: '¿ANTOJOS?',
    defaultLocation: 'UBICACIÓN PREDETERMINADA',
    subCravings: '¿Qué se te antoja hoy?',
    searchPlaceholder: 'Buscar restaurantes, cocinas o platillos...',
    whatsOnMind: '¿QUÉ TIENES EN MENTE?',
    topRestaurants: 'LOS MEJORES RESTAURANTES CERCA DE TI',
    restaurantsExplore: 'RESTAURANTES PARA EXPLORAR AHORA',
    filters: 'FILTROS',
    sort: 'ORDENAR',
    kitchenDashboard: 'Panel de Cocina',
    driverPortal: 'Portal de Repartidor',
    cat_Idli: 'Idli',
    cat_Dosa: 'Dosa',
    cat_Biryani: 'Biryani',
    cat_Meals: 'Comidas',
    cat_Sweets: 'Postres',
    cat_Snacks: 'Bocadillos',
    cat_Chaat: 'Chaat',
    cat_Coffee: 'Café',

    // Settings Keys
    settingsTitle: 'Ajustes y Perfil',
    settingsSub: 'CONFIGURACIÓN DE USUARIO',
    accountProfile: 'Cuenta y Perfil',
    langRegional: 'Idioma y Región',
    locRadius: 'Ubicación y Radio',
    pushNotifications: 'Notificaciones Push',
    appearanceTheme: 'Apariencia y Tema',
    mapsNav: 'Mapas y Navegación',
    paymentsHist: 'Pagos e Historial',
    rewardsPassport: 'Recompensas y Pasaporte',
    socialFriends: 'Amigos y Redes',
    privacySecurity: 'Privacidad y Seguridad',
    supportFeedback: 'Soporte y Comentarios',
    legalNorms: 'Legal (Normas)',
    aboutEats: 'Acerca de Hidden Eats',
    saveSettings: 'Guardar Ajustes y Preferencias',
    primaryLangLabel: 'Idioma Principal del Sitio (7 Idiomas)',
    primaryLangSub: 'Selecciona tu idioma preferido para traducción instantánea.',
    autoGoogleLabel: 'Traducción Automática de Google (100+ Idiomas)',
    autoGoogleSub: 'Traduce reseñas de usuarios a más de 100 idiomas.',
    currencyDisplay: 'Moneda Preferida',
  },
  fr: {
    exploreSpots: 'EXPLORER LES RESTOS',
    inAppMap: 'CARTE',
    liveRadar: 'RADAR EN DIRECT',
    foodieReels: 'REELS GOURMANDS',
    collections: 'COLLECTIONS',
    cravings: 'UNE ENVIE ?',
    defaultLocation: 'EMPLACEMENT PAR DÉFAUT',
    subCravings: 'De quoi avez-vous envie aujourd’hui ?',
    searchPlaceholder: 'Rechercher des restaurants, cuisines ou plats...',
    whatsOnMind: 'QUE VOULEZ-VOUS MANGER ?',
    topRestaurants: 'MEILLEURS RESTAURANTS À PROXIMITÉ',
    restaurantsExplore: 'RESTAURANTS À DÉCOUVRIR MAINTENANT',
    filters: 'FILTRES',
    sort: 'TRIER',
    kitchenDashboard: 'Tableau de Cuisine',
    driverPortal: 'Portail Livreurs',
    cat_Idli: 'Idli',
    cat_Dosa: 'Dosa',
    cat_Biryani: 'Biryani',
    cat_Meals: 'Repas',
    cat_Sweets: 'Desserts',
    cat_Snacks: 'Encas',
    cat_Chaat: 'Chaat',
    cat_Coffee: 'Café',

    // Settings Keys
    settingsTitle: 'Réglages et Profil',
    settingsSub: 'CONFIGURATION DE L\'ESPACE UTILISATEUR',
    accountProfile: 'Compte et Profil',
    langRegional: 'Langue et Région',
    locRadius: 'Localisation et Rayon',
    pushNotifications: 'Notifications Push',
    appearanceTheme: 'Apparence et Thème',
    mapsNav: 'Cartes et Navigation',
    paymentsHist: 'Paiements et Historique',
    rewardsPassport: 'Récompenses et Passeport',
    socialFriends: 'Amis et Réseau',
    privacySecurity: 'Confidentialité et Sécurité',
    supportFeedback: 'Support et Avis',
    legalNorms: 'Mentions Légales',
    aboutEats: 'À propos de Hidden Eats',
    saveSettings: 'Enregistrer les Réglages',
    primaryLangLabel: 'Langue Principale (7 Langues)',
    primaryLangSub: 'Sélectionnez votre langue pour une traduction instantanée.',
    autoGoogleLabel: 'Traduction Automatique Google (100+ Langues)',
    autoGoogleSub: 'Traduit les avis dans plus de 100 langues.',
    currencyDisplay: 'Devise Préférée',
  },
  ar: {
    exploreSpots: 'استكشاف المطاعم',
    inAppMap: 'الخريطة',
    liveRadar: 'الرادار المباشر',
    foodieReels: 'مقاطع الطعام',
    collections: 'المجموعات',
    cravings: 'هل تشعر بالجوع؟',
    defaultLocation: 'الموقع الافتراضي',
    subCravings: 'ماذا تشتهي اليوم؟',
    searchPlaceholder: 'ابحث عن المطاعم، المأكولات، أو الأطباق...',
    whatsOnMind: 'ماذا تريد أن تأكل اليوم؟',
    topRestaurants: 'أفضل المطاعم القريبة منك',
    restaurantsExplore: 'مطاعم يمكن استكشافها الآن',
    filters: 'تصفية',
    sort: 'ترتيب',
    kitchenDashboard: 'لوحة المطبخ',
    driverPortal: 'بوابة التوصيل',
    cat_Idli: 'إدلي',
    cat_Dosa: 'دوسا',
    cat_Biryani: 'برياني',
    cat_Meals: 'وجبات',
    cat_Sweets: 'حلويات',
    cat_Snacks: 'وجبات خفيفة',
    cat_Chaat: 'تشات',
    cat_Coffee: 'قهوة',

    // Settings Keys
    settingsTitle: 'الإعدادات والملف الشخصي',
    settingsSub: 'تكوين مساحة المستخدم',
    accountProfile: 'الحساب والملف الشخصي',
    langRegional: 'اللغة والمنطقة',
    locRadius: 'الموقع والنطاق',
    pushNotifications: 'الإشعارات المباشرة',
    appearanceTheme: 'المظهر والسمة',
    mapsNav: 'الخرائط والتنقل',
    paymentsHist: 'المدفوعات والسجل',
    rewardsPassport: 'المكافآت والجواز',
    socialFriends: 'الأصدقاء والتواصل',
    privacySecurity: 'الخصوصية والأمان',
    supportFeedback: 'الدعم والملاحظات',
    legalNorms: 'القانونية',
    aboutEats: 'عن Hidden Eats',
    saveSettings: 'حفظ جميع الإعدادات',
    primaryLangLabel: 'لغة الموقع الرئيسية (7 لغات مختارة)',
    primaryLangSub: 'اختر لغتك المفضلة للترجمة الفورية.',
    autoGoogleLabel: 'ترجمة جوجل الآلية (100+ لغة)',
    autoGoogleSub: 'ترجمة مراجعات المستخدمين تلقائيًا.',
    currencyDisplay: 'العملة المفضلة',
  },
  ja: {
    exploreSpots: 'スポットを検索',
    inAppMap: 'マップ',
    liveRadar: 'ライブラダー',
    foodieReels: 'グルメショーツ',
    collections: 'コレクション',
    cravings: 'お腹が空きましたか？',
    defaultLocation: 'デフォルトの場所',
    subCravings: '今日は何が食べたいですか？',
    searchPlaceholder: 'レストラン、料理、メニューを検索...',
    whatsOnMind: '今日の気分は？',
    topRestaurants: '近くのトップレストラン',
    restaurantsExplore: '今すぐ探すレストラン',
    filters: 'フィルター',
    sort: '並び替え',
    kitchenDashboard: '厨房ダッシュボード',
    driverPortal: '配達ポータル',
    cat_Idli: 'イドゥリ',
    cat_Dosa: 'ドーサ',
    cat_Biryani: 'ビリヤニ',
    cat_Meals: 'ミールス',
    cat_Sweets: 'スイーツ',
    cat_Snacks: 'スナック',
    cat_Chaat: 'チャート',
    cat_Coffee: 'コーヒー',

    // Settings Keys
    settingsTitle: '設定とプロフィール',
    settingsSub: 'ユーザー設定',
    accountProfile: 'アカウントとプロフィール',
    langRegional: '言語と地域',
    locRadius: '位置情報と検索範囲',
    pushNotifications: 'プッシュ通知',
    appearanceTheme: '外観とテーマ',
    mapsNav: 'マップとナビゲーション',
    paymentsHist: 'お支払いと履歴',
    rewardsPassport: 'リワードとパスポート',
    socialFriends: '友達とソーシャル',
    privacySecurity: 'プライバシーとセキュリティ',
    supportFeedback: 'サポートとフィードバック',
    legalNorms: '法的記述',
    aboutEats: 'Hidden Eatsについて',
    saveSettings: 'すべての設定を保存',
    primaryLangLabel: '主言語設定（7言語対応）',
    primaryLangSub: '即時翻訳に使用する言語を選択してください。',
    autoGoogleLabel: 'Google自動翻訳 (100言語以上)',
    autoGoogleSub: 'ユーザーレビューを100以上の言語に自動翻訳します。',
    currencyDisplay: '表示通貨設定',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<SupportedLanguage>('en');

  useEffect(() => {
    const saved = localStorage.getItem('hidden_eats_lang') as SupportedLanguage;
    if (saved && DICTIONARY[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('hidden_eats_lang', lang);
  };

  const t = (key: string): string => {
    const langDict = DICTIONARY[language] || DICTIONARY.en;
    return langDict[key] || DICTIONARY.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
